@API_HostAddress = http://localhost:5057

GET {{API_HostAddress}}/api/client/AllActiveClients

###

DELETE {{API_HostAddress}}/api/client/DeleteClientById

###

POST {{API_HostAddress}}/api/client/CreateClient
Content-Type: application/json

{
  //ClientCreateRequestDTO
}

###

GET {{API_HostAddress}}/system/warmup

###

GET {{API_HostAddress}}/api/client/AllActiveClients

###
